# name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - main

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: wsnash-homelab/${{ github.event.repository.name }}

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Log in to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ${{ env.REGISTRY }}
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Extract short SHA
#         id: vars
#         run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

#       - name: Build and push image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           platforms: linux/amd64
#           push: true
#           tags: |
#             ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
#             ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
#           cache-from: type=gha
#           cache-to: type=gha,mode=max